### ISSUE TITLE
ng-iban and angular material autocomplete 

### ISSUE THREAD

**Issue by tom94zoe** [mmjmanders/ng-iban#18]
Is there a way to use ng-iban with an autocomplete (angular material 1.1)?

**Comment by tom94zoe** [comment]
I just created a jsfiddle, where I added the directive to input of the autocomplete. 
But it isn't shown as invalid because the class 'md-input-invalid' is missing 
https://jsfiddle.net/p4knm9or/3/

**Comment by mmjmanders** [comment]
The output in the jsfiddle looks fine
