### ISSUE TITLE
Set field to invalid when empty.

### ISSUE THREAD

**Issue by Buffaloketchup** [mmjmanders/ng-iban#3]
Hello,

Your code is great, but it has a little drawback (well, in my case anyway): when the input field is emptied, it is set back to valid. I'd like it to be considered invalid.

I tried to modify the code to prevent that but I cannot figure out how to do. Would you be willing to help me on that?

Cheers in advance,
Thomas

**Comment by FelixWessendorf** [comment]
Hey Thomas,

you should just use the "required"-Attribute in your html to indicate that an empty iban is invalid.

Cheers back,
Felix

**Comment by Buffaloketchup** [comment]
Oh my apologies, I forgot the "required". Feel a bit stupid now... Thanks for the quick answer anyway. Keep up the good work!

**Comment by mmjmanders** [comment]
This has been solved in #2
