### ISSUE TITLE
bower install doesn't give me the right files

### ISSUE THREAD

**Issue by jlvdh** [mmjmanders/ng-iban#4]
running:

    bower install ng-iban

only gives me the following files, which doesn't seem correct:

![screen shot 2015-08-13 at 16 34 29](https://cloud.githubusercontent.com/assets/1208101/9252574/4eb2d216-41d9-11e5-8b06-68d0739ac9bc.png)

**Comment by mmjmanders** [comment]
What is your OS/Bower version? I tried to reproduce this but my directory structure seems fine, i.e. the `ng-iban.js` and `ng-iban.min.js` are downloaded in the `dist` subfolder.

**Comment by Orppa** [comment]
Bower installation on that part goes ok also for me with version 0.4.0, as dist and it's content is installed.

**Comment by mmjmanders** [comment]
Unable to reproduce; closing for now
